### ISSUE TITLE
`compress` attempts to compress responses that are closed - error

### ISSUE THREAD

**Issue by daniel-v** [angel-dart/compress#5]
Pretty much what the title states.

```dart
app.responseFinalizers.add(gzip());
```

**Comment by thosakwe** [comment]
This package isn’t necessary for 1.1.x; it exists for legacy versions. 

Instead, use `app.injectEncoders({'gzip': GZIP.encoder})`.

In 1.2.0, this will be changed to `app.encoders['gzip'] = ...`
